version: '3.5'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '80:80'
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env